// Autogenerated Code - Do not implement custom logic here. 
// Implement custom logic in partial class

using MPR.RestApiTemplate.Domain.Interfaces;
using MPR.RestApiTemplate.Domain.Interfaces.Repositories;
using MPR.RestApiTemplate.Infrastructure.Repositories;

namespace MPR.RestApiTemplate.Infrastructure
{
	public partial class UnitOfWork(): IUnitOfWork
	{

		public virtual async Task<int> SaveChangesAsync() {

			int totalAffectedRows = 0;


			return totalAffectedRows;
		}

		public virtual void Dispose()
		{

			GC.SuppressFinalize(this);
		}
	}
}