// Autogenerated Code - Do not implement custom logic here. 
// Implement custom logic in partial class

using MPR.RestApiTemplate.Domain.Interfaces;
using MPR.RestApiTemplate.Domain.Interfaces.Repositories;
using MPR.RestApiTemplate.Infrastructure.Context;
using MPR.RestApiTemplate.Infrastructure.Repositories;

namespace MPR.RestApiTemplate.Infrastructure
{
	public partial class UnitOfWork(DefaultDbContext defaultDbContext): IUnitOfWork
	{
		private readonly DefaultDbContext _defaultDbContext = defaultDbContext;

		private ICustomerRepository? _customerRepository;
		private ICustomerTypeRepository? _customerTypeRepository;

		public ICustomerRepository CustomerRepository => _customerRepository ??= new CustomerRepository(_defaultDbContext);
		public ICustomerTypeRepository CustomerTypeRepository => _customerTypeRepository ??= new CustomerTypeRepository(_defaultDbContext);

		public virtual async Task<int> SaveChangesAsync() {
			int defaultDbContextAffectedRows =  await _defaultDbContext.SaveChangesAsync();

			int totalAffectedRows = 0;
			totalAffectedRows += defaultDbContextAffectedRows;

			return totalAffectedRows;
		}

		public virtual void Dispose()
		{
			_defaultDbContext.Dispose();
			GC.SuppressFinalize(this);
		}
	}
}