// Autogenerated Code - Do not implement custom logic here. 
// Implement custom logic in partial class

using MPR.RestApiTemplate.Domain.Interfaces;
using MPR.RestApiTemplate.Domain.Interfaces.Repositories;
using MPR.RestApiTemplate.Infrastructure.Context;
using MPR.RestApiTemplate.Infrastructure.Repositories;

namespace MPR.RestApiTemplate.Infrastructure
{
	public partial class UnitOfWork(HrContext hrContext): IUnitOfWork
	{
		private readonly HrContext _hrContext = hrContext;

		private IHrContextSqlExecutor? _hrContextSqlExecutor;
		private ICountryRepository? _countryRepository;
		private IDepartmentRepository? _departmentRepository;
		private IEmployeeRepository? _employeeRepository;
		private IEmpDetailsViewRepository? _empDetailsViewRepository;
		private IJobRepository? _jobRepository;
		private IJobHistoryRepository? _jobHistoryRepository;
		private ILocationRepository? _locationRepository;
		private IRegionRepository? _regionRepository;

		public IHrContextSqlExecutor HrContextSqlExecutor => _hrContextSqlExecutor ??= new HrContextSqlExecutor(_hrContext);
		public ICountryRepository CountryRepository => _countryRepository ??= new CountryRepository(_hrContext);
		public IDepartmentRepository DepartmentRepository => _departmentRepository ??= new DepartmentRepository(_hrContext);
		public IEmployeeRepository EmployeeRepository => _employeeRepository ??= new EmployeeRepository(_hrContext);
		public IEmpDetailsViewRepository EmpDetailsViewRepository => _empDetailsViewRepository ??= new EmpDetailsViewRepository(_hrContext);
		public IJobRepository JobRepository => _jobRepository ??= new JobRepository(_hrContext);
		public IJobHistoryRepository JobHistoryRepository => _jobHistoryRepository ??= new JobHistoryRepository(_hrContext);
		public ILocationRepository LocationRepository => _locationRepository ??= new LocationRepository(_hrContext);
		public IRegionRepository RegionRepository => _regionRepository ??= new RegionRepository(_hrContext);

		public virtual async Task<int> SaveChangesAsync() {
			int hrContextAffectedRows =  await _hrContext.SaveChangesAsync();

			int totalAffectedRows = 0;
			totalAffectedRows += hrContextAffectedRows;

			return totalAffectedRows;
		}

		public virtual void Dispose()
		{
			_hrContext.Dispose();
			GC.SuppressFinalize(this);
		}
	}
}