// Autogenerated Code - Do not modify
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public class CurrentProductListDto
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
    }
}
