// Autogenerated Code - Do not modify
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public class CustomerAndSuppliersByCityDto
    {
        public string? City { get; set; }
        public string CompanyName { get; set; }
        public string? ContactName { get; set; }
        public string Relationship { get; set; }
    }
}
