// Autogenerated Code - Do not modify
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public class OrderDetailsDto
    {
        [Key]
        public int OrderId { get; set; }
        [Key]
        public int ProductId { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public int Withhold { get; set; }
        public float Discount { get; set; }
        public OrdersDto Order { get; set; }
        public ProductsDto Product { get; set; }
    }
}
