// Autogenerated Code - Do not modify
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public class RegionCreateDto
    {
        public int RegionId { get; set; }
        public string RegionDescription { get; set; }
    }
}
