// Autogenerated Code - Do not modify
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public class RegionDto
    {
        [Key]
        public int RegionId { get; set; }
        public string RegionDescription { get; set; }
        public ICollection<TerritoriesDto> Territories { get; set; }
    }
}
