services:
  mpr.restapitemplate.api:
    image: ${DOCKER_REGISTRY-}mpr.restapitemplate
    build:
      context: .
      dockerfile: MPR.RestApiTemplate.Api/Dockerfile
    networks:
      - api-backend-network
    ports:
      - 50080:8080
      - 50443:8081

networks:
  api-backend-network:
    external: true  