<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="app.config" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="app.config">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" Version="6.0.4">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.6.1" />
		<PackageReference Include="xunit" Version="2.9.3" />
		<PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MPR.RestApiTemplate.Security\MPR.RestApiTemplate.Security.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings_test.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Mapfre.URL.SecurityToken">
		  <HintPath>..\libs\Mapfre.URL.SecurityToken.dll</HintPath>
		</Reference>
		<Reference Include="MapfreUserSecurityLibrary">
			<HintPath>..\libs\MapfreUserSecurityLibrary.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
