// Autogenerated Code - Do not implement custom logic here.
// Implement custom logic in partial class

using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces.Repositories;
using MPR.RestApiTemplate.Infrastructure.Context;

namespace MPR.RestApiTemplate.Infrastructure.Repositories
{
    public partial class SuppliersRepository(NorthwindContext northwindContext) : GenericRepository<Suppliers>(northwindContext), ISuppliersRepository
    {
    }
}
