// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class CurrentProductListService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public CurrentProductListService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<CurrentProductListDto>> GetAllAsync(params Expression<Func<CurrentProductList, object>>[] includes)
        {
            var entities = await _unitOfWork.CurrentProductListRepository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<CurrentProductListDto>>(entities);
        }
    }
}
