// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class EmployeesService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public EmployeesService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<EmployeesDto>> GetAllAsync(params Expression<Func<Employees, object>>[] includes)
        {
            var entities = await _unitOfWork.EmployeesRepository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<EmployeesDto>>(entities);
        }

        public virtual async Task<EmployeesDto> GetByIdAsync(int employeeId, params Expression<Func<Employees, object>>[] includes)
        {
            var entity = await _unitOfWork.EmployeesRepository.GetByIdAsync(new object[] { employeeId }, includes);
            return _mapper.Map<EmployeesDto>(entity);
        }

        public virtual async Task DeleteAsync(int employeeId)
        {
            await _unitOfWork.EmployeesRepository.DeleteAsync(employeeId);
            await _unitOfWork.SaveChangesAsync();
        }

        public virtual async Task<EmployeesDto> AddAsync(EmployeesCreateDto model)
        {
            var entity = _mapper.Map<Employees>(model);
            entity = await _unitOfWork.EmployeesRepository.AddAsync(entity);
            await _unitOfWork.SaveChangesAsync();
            return _mapper.Map<EmployeesDto>(entity);
        }

        public virtual async Task<EmployeesDto> UpdateAsync(EmployeesUpdateDto model)
        {
            var entity = _mapper.Map<Employees>(model);
            entity = await _unitOfWork.EmployeesRepository.UpdateAsync(entity);
            await _unitOfWork.SaveChangesAsync();
            return _mapper.Map<EmployeesDto>(entity);
        }
    }
}
