// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class OrdersService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public OrdersService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<OrdersDto>> GetAllAsync(params Expression<Func<Orders, object>>[] includes)
        {
            var entities = await _unitOfWork.OrdersRepository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<OrdersDto>>(entities);
        }

        public virtual async Task<OrdersDto> GetByIdAsync(int orderId, params Expression<Func<Orders, object>>[] includes)
        {
            var entity = await _unitOfWork.OrdersRepository.GetByIdAsync(new object[] { orderId }, includes);
            return _mapper.Map<OrdersDto>(entity);
        }

        public virtual async Task DeleteAsync(int orderId)
        {
            await _unitOfWork.OrdersRepository.DeleteAsync(orderId);
            await _unitOfWork.SaveChangesAsync();
        }

        public virtual async Task<OrdersDto> AddAsync(OrdersCreateDto model)
        {
            var entity = _mapper.Map<Orders>(model);
            entity = await _unitOfWork.OrdersRepository.AddAsync(entity);
            await _unitOfWork.SaveChangesAsync();
            return _mapper.Map<OrdersDto>(entity);
        }

        public virtual async Task<OrdersDto> UpdateAsync(OrdersUpdateDto model)
        {
            var entity = _mapper.Map<Orders>(model);
            entity = await _unitOfWork.OrdersRepository.UpdateAsync(entity);
            await _unitOfWork.SaveChangesAsync();
            return _mapper.Map<OrdersDto>(entity);
        }
    }
}
