// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class OrderDetailsExtendedService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public OrderDetailsExtendedService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<OrderDetailsExtendedDto>> GetAllAsync(params Expression<Func<OrderDetailsExtended, object>>[] includes)
        {
            var entities = await _unitOfWork.OrderDetailsExtendedRepository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<OrderDetailsExtendedDto>>(entities);
        }
    }
}
