// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class ProductSalesFor1997Service
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public ProductSalesFor1997Service(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<ProductSalesFor1997Dto>> GetAllAsync(params Expression<Func<ProductSalesFor1997, object>>[] includes)
        {
            var entities = await _unitOfWork.ProductSalesFor1997Repository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<ProductSalesFor1997Dto>>(entities);
        }
    }
}
