// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class ProductsByCategoryService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public ProductsByCategoryService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<ProductsByCategoryDto>> GetAllAsync(params Expression<Func<ProductsByCategory, object>>[] includes)
        {
            var entities = await _unitOfWork.ProductsByCategoryRepository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<ProductsByCategoryDto>>(entities);
        }
    }
}
