// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;
using MPR.RestApiTemplate.Domain.Interfaces;
using System.Linq.Expressions;

namespace MPR.RestApiTemplate.Application.Services
{
    public partial class SalesByCategoryService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public SalesByCategoryService(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public virtual async Task<IEnumerable<SalesByCategoryDto>> GetAllAsync(params Expression<Func<SalesByCategory, object>>[] includes)
        {
            var entities = await _unitOfWork.SalesByCategoryRepository.GetAllAsync(includes);
            return _mapper.Map<IEnumerable<SalesByCategoryDto>>(entities);
        }
    }
}
