<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.3" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Mapfre.URL.SecurityToken">
      <HintPath>..\libs\Mapfre.URL.SecurityToken.dll</HintPath>
    </Reference>
    <Reference Include="MapfreUserSecurityLibrary">
      <HintPath>..\libs\MapfreUserSecurityLibrary.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
