// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public partial class CategoriesMapping : Profile
    {
        public CategoriesMapping()
        {
            ConfigureMappings();
        }

        protected virtual void ConfigureMappings()
        {
            CreateMap<Categories, CategoriesDto>().ReverseMap();
            CreateMap<Categories, CategoriesCreateDto>().ReverseMap();
            CreateMap<Categories, CategoriesUpdateDto>().ReverseMap();
        }
    }
}
