// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public partial class CategorySalesFor1997Mapping : Profile
    {
        public CategorySalesFor1997Mapping()
        {
            ConfigureMappings();
        }

        protected virtual void ConfigureMappings()
        {
            CreateMap<CategorySalesFor1997, CategorySalesFor1997Dto>().ReverseMap();
        }
    }
}
