// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public partial class CustomerDemographicsMapping : Profile
    {
        public CustomerDemographicsMapping()
        {
            ConfigureMappings();
        }

        protected virtual void ConfigureMappings()
        {
            CreateMap<CustomerDemographics, CustomerDemographicsDto>().ReverseMap();
            CreateMap<CustomerDemographics, CustomerDemographicsCreateDto>().ReverseMap();
            CreateMap<CustomerDemographics, CustomerDemographicsUpdateDto>().ReverseMap();
        }
    }
}
