// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public partial class EmployeesMapping : Profile
    {
        public EmployeesMapping()
        {
            ConfigureMappings();
        }

        protected virtual void ConfigureMappings()
        {
            CreateMap<Employees, EmployeesDto>().ReverseMap();
            CreateMap<Employees, EmployeesCreateDto>().ReverseMap();
            CreateMap<Employees, EmployeesUpdateDto>().ReverseMap();
        }
    }
}
