// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public partial class ProductsMapping : Profile
    {
        public ProductsMapping()
        {
            ConfigureMappings();
        }

        protected virtual void ConfigureMappings()
        {
            CreateMap<Products, ProductsDto>().ReverseMap();
            CreateMap<Products, ProductsCreateDto>().ReverseMap();
            CreateMap<Products, ProductsUpdateDto>().ReverseMap();
        }
    }
}
