// Autogenerated Code - Do not modify
using AutoMapper;
using MPR.RestApiTemplate.Application.DTOs;
using MPR.RestApiTemplate.Domain.Entities;

namespace MPR.RestApiTemplate.Application.DTOs
{
    public partial class RegionMapping : Profile
    {
        public RegionMapping()
        {
            ConfigureMappings();
        }

        protected virtual void ConfigureMappings()
        {
            CreateMap<Region, RegionDto>().ReverseMap();
            CreateMap<Region, RegionCreateDto>().ReverseMap();
            CreateMap<Region, RegionUpdateDto>().ReverseMap();
        }
    }
}
